"""Aumentar tamanho de campos em Regras

Revision ID: 13cad3de079f
Revises: 36d6e1face28
Create Date: 2026-06-27 08:59:14.989923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13cad3de079f'
down_revision: Union[str, Sequence[str], None] = '36d6e1face28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regras_obrigacoes', 'departamento',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_comment='CONTABIL, FISCAL, PESSOAL, SOCIETARIO',
               existing_nullable=True)
    op.alter_column('regras_obrigacoes', 'regime',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_comment='Filtro de regime tributário',
               existing_nullable=True)
    op.alter_column('regras_obrigacoes', 'acao',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_comment='ENVIAR, ARQUIVAR, AUDITAR, COMUNICAR',
               existing_nullable=True)
    op.alter_column('regras_obrigacoes', 'meses',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_comment="Meses aplicáveis (ex: '1,2,3...12')",
               existing_nullable=True)
    op.alter_column('regras_obrigacoes', 'tipos',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_comment='Tipos de empresa aplicáveis',
               existing_nullable=True)
    op.alter_column('regras_obrigacoes', 'vencimento_legal',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_comment='Data legal de referência',
               existing_nullable=True)
    op.alter_column('regras_obrigacoes', 'grupo_regra',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_comment='Agrupamento/Tag de regras',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regras_obrigacoes', 'grupo_regra',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_comment='Agrupamento/Tag de regras',
               existing_nullable=True)
    op.alter_column('regras_obrigacoes', 'vencimento_legal',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_comment='Data legal de referência',
               existing_nullable=True)
    op.alter_column('regras_obrigacoes', 'tipos',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_comment='Tipos de empresa aplicáveis',
               existing_nullable=True)
    op.alter_column('regras_obrigacoes', 'meses',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_comment="Meses aplicáveis (ex: '1,2,3...12')",
               existing_nullable=True)
    op.alter_column('regras_obrigacoes', 'acao',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_comment='ENVIAR, ARQUIVAR, AUDITAR, COMUNICAR',
               existing_nullable=True)
    op.alter_column('regras_obrigacoes', 'regime',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_comment='Filtro de regime tributário',
               existing_nullable=True)
    op.alter_column('regras_obrigacoes', 'departamento',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_comment='CONTABIL, FISCAL, PESSOAL, SOCIETARIO',
               existing_nullable=True)
    # ### end Alembic commands ###
