"""tabelas_equipes

Revision ID: 36d6e1face28
Revises: 588599575637
Create Date: 2026-06-10 14:14:53.007529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d6e1face28'
down_revision: Union[str, Sequence[str], None] = '588599575637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False, comment='Nome da equipe (ex: Equipe Fiscal A)'),
    sa.Column('departamento', sa.String(length=50), nullable=False, comment='Departamento (FISCAL, CONTABIL, PESSOAL, SOCIETARIO)'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Equipes de trabalho (Squads) por departamento'
    )
    op.create_index(op.f('ix_equipes_tenant_id'), 'equipes', ['tenant_id'], unique=False)
    op.create_table('usuarios_equipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipe_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Relacionamento N:N entre Usuários e Equipes'
    )
    op.create_index(op.f('ix_usuarios_equipes_tenant_id'), 'usuarios_equipes', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_equipes_tenant_id'), table_name='usuarios_equipes')
    op.drop_table('usuarios_equipes')
    op.drop_index(op.f('ix_equipes_tenant_id'), table_name='equipes')
    op.drop_table('equipes')
    # ### end Alembic commands ###
