"""Add tipos_tarefa_avulsa

Revision ID: 588599575637
Revises: cb21e32a9504
Create Date: 2026-06-02 10:32:42.286436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588599575637'
down_revision: Union[str, Sequence[str], None] = 'cb21e32a9504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('data_entrada', sa.Date(), nullable=True, comment='Data de entrada do cliente na carteira. Tarefas não serão geradas para competências anteriores a este mês.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'data_entrada')
    # ### end Alembic commands ###
