"""Add documentos societarios

Revision ID: 5cc2f085b05a
Revises: 615869f798bf
Create Date: 2026-07-09 08:22:41.312672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc2f085b05a'
down_revision: Union[str, Sequence[str], None] = '615869f798bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alvaras_sanitarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('arquivo_url', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alvaras_sanitarios_tenant_id'), 'alvaras_sanitarios', ['tenant_id'], unique=False)
    op.create_table('avcbs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('arquivo_url', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avcbs_tenant_id'), 'avcbs', ['tenant_id'], unique=False)
    op.create_table('inscricoes_municipais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('arquivo_url', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inscricoes_municipais_tenant_id'), 'inscricoes_municipais', ['tenant_id'], unique=False)
    op.create_table('licencas_localizacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('arquivo_url', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licencas_localizacao_tenant_id'), 'licencas_localizacao', ['tenant_id'], unique=False)
    op.alter_column('clientes', 'chaves_acesso',
               existing_type=sa.TEXT(),
               comment="JSON mapping: {'email': {'hash': '...', 'gerada_em': '...'}}",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'chaves_acesso',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="JSON mapping: {'email': {'hash': '...', 'gerada_em': '...'}}",
               existing_nullable=True)
    op.drop_index(op.f('ix_licencas_localizacao_tenant_id'), table_name='licencas_localizacao')
    op.drop_table('licencas_localizacao')
    op.drop_index(op.f('ix_inscricoes_municipais_tenant_id'), table_name='inscricoes_municipais')
    op.drop_table('inscricoes_municipais')
    op.drop_index(op.f('ix_avcbs_tenant_id'), table_name='avcbs')
    op.drop_table('avcbs')
    op.drop_index(op.f('ix_alvaras_sanitarios_tenant_id'), table_name='alvaras_sanitarios')
    op.drop_table('alvaras_sanitarios')
    # ### end Alembic commands ###
