"""add_portal_access_key_and_login_attempts

Revision ID: 615869f798bf
Revises: 692805662134
Create Date: 2026-07-08 13:08:28.109253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615869f798bf'
down_revision: Union[str, Sequence[str], None] = '692805662134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tentativas_login',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='Endereco IP da tentativa (suporta IPv4 e IPv6)'),
    sa.Column('attempt_time', sa.DateTime(timezone=True), nullable=False, comment='Data/hora da tentativa falha'),
    sa.Column('documento', sa.String(length=20), nullable=True, comment='CPF/CNPJ tentado'),
    sa.PrimaryKeyConstraint('id'),
    comment='Registro de tentativas de login falhas por IP para rate limiting'
    )
    op.create_index(op.f('ix_tentativas_login_ip_address'), 'tentativas_login', ['ip_address'], unique=False)
    op.add_column('clientes', sa.Column('chave_portal_hash', sa.String(length=255), nullable=True, comment='Hash bcrypt da chave de acesso ao portal'))
    op.add_column('clientes', sa.Column('chave_portal_gerada_em', sa.DateTime(timezone=True), nullable=True, comment='Data de geracao da ultima chave'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'chave_portal_gerada_em')
    op.drop_column('clientes', 'chave_portal_hash')
    op.drop_index(op.f('ix_tentativas_login_ip_address'), table_name='tentativas_login')
    op.drop_table('tentativas_login')
    # ### end Alembic commands ###
