"""add solicitacao_recorrente

Revision ID: 692805662134
Revises: c0b0d99fbdda
Create Date: 2026-07-06 10:25:54.880347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692805662134'
down_revision: Union[str, Sequence[str], None] = 'c0b0d99fbdda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacoes_recorrentes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False, comment='Referência ao ID do cliente'),
    sa.Column('cliente_nome', sa.String(length=255), nullable=False, comment='Nome do cliente (desnormalizado para busca)'),
    sa.Column('departamento', sa.String(length=50), nullable=False, comment='Departamento responsável (Fiscal, Contábil, etc)'),
    sa.Column('responsavel', sa.String(length=255), nullable=False, comment='Email do responsável pela solicitação'),
    sa.Column('email_override', sa.String(length=255), nullable=True, comment='Se preenchido, sobrepõe o email do cliente/departamento'),
    sa.Column('titulo_template', sa.String(length=255), nullable=False, comment='Ex: Extratos Bancários do mês {mes_anterior}/{ano_anterior}'),
    sa.Column('descricao_template', sa.Text(), nullable=True, comment='Corpo da solicitação com suporte a variáveis de template'),
    sa.Column('dia_geracao', sa.Integer(), nullable=False, comment='Dia do mês para gerar (ex: 3)'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Se a regra está ativa'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Configuração de solicitações mensais/semanais geradas automaticamente'
    )
    op.create_index(op.f('ix_solicitacoes_recorrentes_cliente_id'), 'solicitacoes_recorrentes', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_recorrentes_tenant_id'), 'solicitacoes_recorrentes', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitacoes_recorrentes_tenant_id'), table_name='solicitacoes_recorrentes')
    op.drop_index(op.f('ix_solicitacoes_recorrentes_cliente_id'), table_name='solicitacoes_recorrentes')
    op.drop_table('solicitacoes_recorrentes')
    # ### end Alembic commands ###
