"""Initial schema

Revision ID: 920ad4669525
Revises: 
Create Date: 2026-05-21 11:22:03.193339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920ad4669525'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False, comment='Nome da configuração'),
    sa.Column('valor', sa.Text(), nullable=True, comment='Valor da configuração'),
    sa.PrimaryKeyConstraint('id'),
    comment='Configurações do sistema em formato chave/valor'
    )
    op.create_index(op.f('ix_configuracoes_chave'), 'configuracoes', ['chave'], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False, comment='Razão social do escritório'),
    sa.Column('cnpj', sa.String(length=20), nullable=True, comment='CNPJ do escritório'),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True, comment='Nome fantasia'),
    sa.Column('logo_url', sa.Text(), nullable=True, comment='URL do logotipo (White-label)'),
    sa.Column('cor_primaria', sa.String(length=10), nullable=True, comment='Cor primária da interface'),
    sa.Column('plano', sa.String(length=20), nullable=False, comment='FREE, PRO, ENTERPRISE'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Escritório ativo/inativo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    comment='Escritórios contábeis (raiz multi-tenant)'
    )
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente', sa.String(length=255), nullable=False, comment='Razão social do cliente'),
    sa.Column('cnpj', sa.String(length=20), nullable=True, comment='CNPJ (com ou sem máscara)'),
    sa.Column('responsavel', sa.String(length=255), nullable=True, comment='Nome do responsável no cliente'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email principal de contato'),
    sa.Column('telefone', sa.String(length=255), nullable=True, comment='Telefones (separados por ,;/)'),
    sa.Column('regime', sa.String(length=50), nullable=True, comment='Regime tributário: SIMPLES, LUCRO PRESUMIDO, etc.'),
    sa.Column('fiscal', sa.String(length=255), nullable=True, comment='Referência do setor Fiscal'),
    sa.Column('contabil', sa.String(length=255), nullable=True, comment='Referência do setor Contábil'),
    sa.Column('pessoal', sa.String(length=255), nullable=True, comment='Referência do setor Pessoal'),
    sa.Column('societario', sa.String(length=255), nullable=True, comment='Referência do setor Societário'),
    sa.Column('excecoes', sa.Text(), nullable=True, comment='IDs de regras excluídas para este cliente'),
    sa.Column('pasta_drive', sa.Text(), nullable=True, comment='URL da pasta no Google Drive'),
    sa.Column('nivel', sa.Integer(), nullable=True, comment='Nível de prioridade do cliente'),
    sa.Column('perfis_ativos', sa.Text(), nullable=True, comment='Tags/Perfis de regras aplicáveis'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='ATIVO / INATIVO'),
    sa.Column('email_fiscal', sa.String(length=255), nullable=True, comment='Email de roteamento — Fiscal'),
    sa.Column('email_contabil', sa.String(length=255), nullable=True, comment='Email de roteamento — Contábil'),
    sa.Column('email_pessoal', sa.String(length=255), nullable=True, comment='Email de roteamento — Pessoal'),
    sa.Column('email_societario', sa.String(length=255), nullable=True, comment='Email de roteamento — Societário'),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True, comment='Nome fantasia da empresa'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Clientes (empresas atendidas pelo escritório)'
    )
    op.create_index(op.f('ix_clientes_cliente'), 'clientes', ['cliente'], unique=False)
    op.create_index(op.f('ix_clientes_tenant_id'), 'clientes', ['tenant_id'], unique=False)
    op.create_table('frequencia_acessos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False, comment='Data consolidada'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email do usuário'),
    sa.Column('nome', sa.String(length=255), nullable=True, comment='Nome do usuário'),
    sa.Column('tempo_minutos', sa.Integer(), nullable=True, comment='Minutos de atividade no dia'),
    sa.Column('pings', sa.Integer(), nullable=True, comment='Quantidade de heartbeats no dia'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Registro consolidado de tempo de uso diário por usuário'
    )
    op.create_index(op.f('ix_frequencia_acessos_email'), 'frequencia_acessos', ['email'], unique=False)
    op.create_index(op.f('ix_frequencia_acessos_tenant_id'), 'frequencia_acessos', ['tenant_id'], unique=False)
    op.create_table('historico_tarefas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mes_ano', sa.String(length=20), nullable=False),
    sa.Column('cliente', sa.String(length=255), nullable=False),
    sa.Column('obrigacao', sa.String(length=255), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.Column('departamento', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('protocolo', sa.String(length=50), nullable=True),
    sa.Column('acao', sa.String(length=50), nullable=True),
    sa.Column('responsavel', sa.String(length=255), nullable=True),
    sa.Column('id_controle', sa.String(length=50), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('vencimento_legal', sa.Date(), nullable=True),
    sa.Column('status_envio', sa.String(length=50), nullable=True, comment='Copiado de DB_PROTOCOLOS'),
    sa.Column('conf_recto', sa.String(length=100), nullable=True, comment='Confirmação de recebimento'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Arquivo permanente de tarefas concluídas'
    )
    op.create_index(op.f('ix_historico_tarefas_cliente'), 'historico_tarefas', ['cliente'], unique=False)
    op.create_index(op.f('ix_historico_tarefas_id_controle'), 'historico_tarefas', ['id_controle'], unique=False)
    op.create_index(op.f('ix_historico_tarefas_protocolo'), 'historico_tarefas', ['protocolo'], unique=False)
    op.create_index(op.f('ix_historico_tarefas_tenant_id'), 'historico_tarefas', ['tenant_id'], unique=False)
    op.create_table('logs_sistema',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=False, comment='Data/hora do evento'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Quem executou a ação'),
    sa.Column('acao', sa.String(length=100), nullable=False, comment='Tipo do evento (ex: UPLOAD_START)'),
    sa.Column('detalhes', sa.Text(), nullable=True, comment='Informação adicional'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Logs de auditoria, erros e operações do sistema'
    )
    op.create_index(op.f('ix_logs_sistema_acao'), 'logs_sistema', ['acao'], unique=False)
    op.create_index(op.f('ix_logs_sistema_email'), 'logs_sistema', ['email'], unique=False)
    op.create_index(op.f('ix_logs_sistema_tenant_id'), 'logs_sistema', ['tenant_id'], unique=False)
    op.create_table('protocolos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=False, comment='Data/hora do registro'),
    sa.Column('cliente', sa.String(length=255), nullable=False, comment='Nome do cliente'),
    sa.Column('protocolo', sa.String(length=50), nullable=False, comment='Código único (PRT...)'),
    sa.Column('id_tarefa', sa.String(length=50), nullable=True, comment='Referência ao id_controle da tarefa'),
    sa.Column('obrigacao', sa.String(length=255), nullable=True, comment='Nome da obrigação entregue'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email de destino'),
    sa.Column('responsavel', sa.String(length=255), nullable=True, comment='Quem realizou a entrega'),
    sa.Column('link_arquivo', sa.Text(), nullable=True, comment='URL(s) dos arquivos ou justificativa'),
    sa.Column('status_envio', sa.String(length=50), nullable=True, comment='ENVIADO, MANUAL, ERRO'),
    sa.Column('conf_recto', sa.DateTime(timezone=True), nullable=True, comment='Data de confirmação de recebimento'),
    sa.Column('vcto_legal', sa.Date(), nullable=True, comment='Vencimento legal da obrigação'),
    sa.Column('acao', sa.String(length=50), nullable=True, comment='ENVIAR, ARQUIVAR, COMUNICAR, AUDITAR'),
    sa.Column('wpp_notif', sa.DateTime(timezone=True), nullable=True, comment='Última notificação WhatsApp enviada'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Registro de entregas e protocolos gerados'
    )
    op.create_index(op.f('ix_protocolos_cliente'), 'protocolos', ['cliente'], unique=False)
    op.create_index(op.f('ix_protocolos_id_tarefa'), 'protocolos', ['id_tarefa'], unique=False)
    op.create_index(op.f('ix_protocolos_protocolo'), 'protocolos', ['protocolo'], unique=True)
    op.create_index(op.f('ix_protocolos_tenant_id'), 'protocolos', ['tenant_id'], unique=False)
    op.create_table('regras_obrigacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('obrigacao', sa.String(length=255), nullable=False, comment='Nome da obrigação (ex: DCTF, EFD)'),
    sa.Column('dia', sa.String(length=20), nullable=True, comment="Dia do vencimento (pode ser '5U' para 5º dia útil)"),
    sa.Column('departamento', sa.String(length=50), nullable=True, comment='CONTABIL, FISCAL, PESSOAL, SOCIETARIO'),
    sa.Column('regime', sa.String(length=50), nullable=True, comment='Filtro de regime tributário'),
    sa.Column('acao', sa.String(length=50), nullable=True, comment='ENVIAR, ARQUIVAR, AUDITAR, COMUNICAR'),
    sa.Column('meses', sa.String(length=100), nullable=True, comment="Meses aplicáveis (ex: '1,2,3...12')"),
    sa.Column('tipos', sa.String(length=255), nullable=True, comment='Tipos de empresa aplicáveis'),
    sa.Column('desloca', sa.Integer(), nullable=True, comment='Deslocamento de mês-referência'),
    sa.Column('vencimento_legal', sa.String(length=50), nullable=True, comment='Data legal de referência'),
    sa.Column('antecipa_fds', sa.String(length=10), nullable=True, comment='S/N — antecipa se cair no fim de semana'),
    sa.Column('grupo_regra', sa.String(length=100), nullable=True, comment='Agrupamento/Tag de regras'),
    sa.Column('revisao', sa.String(length=10), nullable=True, comment='S/N — exige revisão do admin antes de finalizar'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Regras que definem obrigações e geram tarefas mensais'
    )
    op.create_index(op.f('ix_regras_obrigacoes_obrigacao'), 'regras_obrigacoes', ['obrigacao'], unique=False)
    op.create_index(op.f('ix_regras_obrigacoes_tenant_id'), 'regras_obrigacoes', ['tenant_id'], unique=False)
    op.create_table('solicitacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_legado', sa.String(length=50), nullable=True, comment='ID original (SOL + timestamp)'),
    sa.Column('data', sa.DateTime(timezone=True), nullable=False, comment='Data da solicitação'),
    sa.Column('cliente', sa.String(length=255), nullable=False, comment='Nome do cliente'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email do cliente'),
    sa.Column('pedido', sa.Text(), nullable=True, comment='Descrição do documento solicitado'),
    sa.Column('id_tarefa', sa.String(length=50), nullable=True, comment="Referência à tarefa (ou 'AVULSA')"),
    sa.Column('status', sa.String(length=20), nullable=True, comment='PENDENTE, ENTREGUE'),
    sa.Column('data_envio', sa.DateTime(timezone=True), nullable=True, comment='Data do envio de resposta'),
    sa.Column('ultima_cobranca', sa.DateTime(timezone=True), nullable=True, comment='Data da última cobrança'),
    sa.Column('qtd_avisos', sa.Integer(), nullable=True, comment='Contador de lembretes enviados'),
    sa.Column('responsavel', sa.String(length=255), nullable=True, comment='Email de quem solicitou'),
    sa.Column('meta_tarefa', sa.String(length=255), nullable=True, comment='Info da tarefa vinculada'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_legado'),
    comment='Solicitações de documentos pendentes dos clientes'
    )
    op.create_index(op.f('ix_solicitacoes_cliente'), 'solicitacoes', ['cliente'], unique=False)
    op.create_index(op.f('ix_solicitacoes_tenant_id'), 'solicitacoes', ['tenant_id'], unique=False)
    op.create_table('tarefas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mes_ano', sa.String(length=20), nullable=False, comment='Referência: MM/YYYY'),
    sa.Column('cliente', sa.String(length=255), nullable=False, comment='Nome do cliente'),
    sa.Column('obrigacao', sa.String(length=255), nullable=False, comment='Nome da obrigação'),
    sa.Column('vencimento', sa.Date(), nullable=True, comment='Data de vencimento operacional'),
    sa.Column('departamento', sa.String(length=50), nullable=True, comment='Departamento responsável'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='PENDENTE, ENTREGUE, REVISAO, REPROVADO'),
    sa.Column('protocolo', sa.String(length=50), nullable=True, comment='Código do protocolo de entrega'),
    sa.Column('acao', sa.String(length=50), nullable=True, comment='ENVIAR, ARQUIVAR, AUDITAR, COMUNICAR'),
    sa.Column('responsavel', sa.String(length=255), nullable=True, comment='Email(s) do(s) responsável(is)'),
    sa.Column('id_controle', sa.String(length=50), nullable=False, comment='Identificador único da tarefa'),
    sa.Column('nivel', sa.Integer(), nullable=True, comment='Prioridade (1-5)'),
    sa.Column('vencimento_legal', sa.Date(), nullable=True, comment='Data legal original do vencimento'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Fila ativa de tarefas pendentes e em andamento'
    )
    op.create_index(op.f('ix_tarefas_cliente'), 'tarefas', ['cliente'], unique=False)
    op.create_index(op.f('ix_tarefas_id_controle'), 'tarefas', ['id_controle'], unique=True)
    op.create_index(op.f('ix_tarefas_status'), 'tarefas', ['status'], unique=False)
    op.create_index(op.f('ix_tarefas_tenant_id'), 'tarefas', ['tenant_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email de login (Google OAuth)'),
    sa.Column('nome', sa.String(length=255), nullable=False, comment='Nome de exibição'),
    sa.Column('nivel', sa.String(length=20), nullable=False, comment='USER, ADMIN, MASTER, CONSULTOR'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Usuário ativo/inativo'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Usuários do sistema (operadores do escritório)'
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=False)
    op.create_index(op.f('ix_usuarios_tenant_id'), 'usuarios', ['tenant_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fase_atual', sa.String(length=100), nullable=False, comment='Nome da fase de origem'),
    sa.Column('proxima_fase', sa.String(length=100), nullable=False, comment='Nome da fase seguinte'),
    sa.Column('dias', sa.Integer(), nullable=True, comment='Prazo em dias para a próxima fase'),
    sa.Column('departamento', sa.String(length=50), nullable=True, comment='Departamento da próxima fase'),
    sa.Column('acao', sa.String(length=50), nullable=True, comment='Ação da próxima fase'),
    sa.Column('responsavel_padrao', sa.String(length=255), nullable=True, comment='Email do responsável padrão'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Regras de encadeamento de fases (workflow)'
    )
    op.create_index(op.f('ix_workflows_tenant_id'), 'workflows', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_tenant_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_usuarios_tenant_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tarefas_tenant_id'), table_name='tarefas')
    op.drop_index(op.f('ix_tarefas_status'), table_name='tarefas')
    op.drop_index(op.f('ix_tarefas_id_controle'), table_name='tarefas')
    op.drop_index(op.f('ix_tarefas_cliente'), table_name='tarefas')
    op.drop_table('tarefas')
    op.drop_index(op.f('ix_solicitacoes_tenant_id'), table_name='solicitacoes')
    op.drop_index(op.f('ix_solicitacoes_cliente'), table_name='solicitacoes')
    op.drop_table('solicitacoes')
    op.drop_index(op.f('ix_regras_obrigacoes_tenant_id'), table_name='regras_obrigacoes')
    op.drop_index(op.f('ix_regras_obrigacoes_obrigacao'), table_name='regras_obrigacoes')
    op.drop_table('regras_obrigacoes')
    op.drop_index(op.f('ix_protocolos_tenant_id'), table_name='protocolos')
    op.drop_index(op.f('ix_protocolos_protocolo'), table_name='protocolos')
    op.drop_index(op.f('ix_protocolos_id_tarefa'), table_name='protocolos')
    op.drop_index(op.f('ix_protocolos_cliente'), table_name='protocolos')
    op.drop_table('protocolos')
    op.drop_index(op.f('ix_logs_sistema_tenant_id'), table_name='logs_sistema')
    op.drop_index(op.f('ix_logs_sistema_email'), table_name='logs_sistema')
    op.drop_index(op.f('ix_logs_sistema_acao'), table_name='logs_sistema')
    op.drop_table('logs_sistema')
    op.drop_index(op.f('ix_historico_tarefas_tenant_id'), table_name='historico_tarefas')
    op.drop_index(op.f('ix_historico_tarefas_protocolo'), table_name='historico_tarefas')
    op.drop_index(op.f('ix_historico_tarefas_id_controle'), table_name='historico_tarefas')
    op.drop_index(op.f('ix_historico_tarefas_cliente'), table_name='historico_tarefas')
    op.drop_table('historico_tarefas')
    op.drop_index(op.f('ix_frequencia_acessos_tenant_id'), table_name='frequencia_acessos')
    op.drop_index(op.f('ix_frequencia_acessos_email'), table_name='frequencia_acessos')
    op.drop_table('frequencia_acessos')
    op.drop_index(op.f('ix_clientes_tenant_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cliente'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_configuracoes_chave'), table_name='configuracoes')
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
