"""Add Perfil

Revision ID: ade9b8561ec8
Revises: 920ad4669525
Create Date: 2026-05-25 13:32:48.523595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade9b8561ec8'
down_revision: Union[str, Sequence[str], None] = '920ad4669525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False, comment='Nome do Perfil'),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='ATIVO / INATIVO'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Perfis de obrigações vinculados aos clientes e regras'
    )
    op.create_index(op.f('ix_perfis_nome'), 'perfis', ['nome'], unique=False)
    op.create_index(op.f('ix_perfis_tenant_id'), 'perfis', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_perfis_tenant_id'), table_name='perfis')
    op.drop_index(op.f('ix_perfis_nome'), table_name='perfis')
    op.drop_table('perfis')
    # ### end Alembic commands ###
