"""Add regras_roteamento to clientes

Revision ID: c0b0d99fbdda
Revises: eb52e1b09590
Create Date: 2026-07-03 13:25:56.781371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0b0d99fbdda'
down_revision: Union[str, Sequence[str], None] = 'eb52e1b09590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('regras_roteamento', sa.Text(), nullable=True, comment="JSON mapping: {'Obrigacao': 'email@destino'}"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'regras_roteamento')
    # ### end Alembic commands ###
