"""Add tipos_tarefa_avulsa

Revision ID: cb21e32a9504
Revises: ade9b8561ec8
Create Date: 2026-05-27 14:09:22.537641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb21e32a9504'
down_revision: Union[str, Sequence[str], None] = 'ade9b8561ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_tarefa_avulsa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False, comment='Nome do tipo (ex: CERTIDÃO NEGATIVA)'),
    sa.Column('departamento', sa.String(length=50), nullable=True, comment='Departamento padrão ao usar este tipo'),
    sa.Column('descricao', sa.String(length=500), nullable=True, comment='Descrição ou instrução sobre este tipo de tarefa'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='ATIVO ou INATIVO'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Catálogo de tipos de tarefas avulsas disponíveis para criação manual'
    )
    op.create_index(op.f('ix_tipos_tarefa_avulsa_nome'), 'tipos_tarefa_avulsa', ['nome'], unique=False)
    op.create_index(op.f('ix_tipos_tarefa_avulsa_tenant_id'), 'tipos_tarefa_avulsa', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipos_tarefa_avulsa_tenant_id'), table_name='tipos_tarefa_avulsa')
    op.drop_index(op.f('ix_tipos_tarefa_avulsa_nome'), table_name='tipos_tarefa_avulsa')
    op.drop_table('tipos_tarefa_avulsa')
    # ### end Alembic commands ###
