"""Add CertificadoDigital

Revision ID: eb52e1b09590
Revises: 13cad3de079f
Create Date: 2026-06-29 11:27:18.531496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb52e1b09590'
down_revision: Union[str, Sequence[str], None] = '13cad3de079f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificados_digitais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data da última atualização'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='ID do escritório proprietário (RLS)'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificados_digitais_tenant_id'), 'certificados_digitais', ['tenant_id'], unique=False)
    op.alter_column('regras_obrigacoes', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='ATIVO ou INATIVO',
               existing_nullable=False,
               existing_server_default=sa.text("'ATIVO'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regras_obrigacoes', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='ATIVO ou INATIVO',
               existing_nullable=False,
               existing_server_default=sa.text("'ATIVO'::character varying"))
    op.drop_index(op.f('ix_certificados_digitais_tenant_id'), table_name='certificados_digitais')
    op.drop_table('certificados_digitais')
    # ### end Alembic commands ###
